[package]
name = "zerofa"
version = "0.1.0"
edition = "2021"

[dependencies]
imap = "2.4"
native-tls = "0.2"
dotenv = "0.15"
tiny_http = "0.12"
regex = "1.11"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"